services:
  template:
    container_name: template-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4123:4123
    restart: always
    volumes:
      - './:/home/node/app'

